// Pure helpers for archive-tour.mjs — the action side of orphan-tour
// detection (lib/prune.mjs finds candidates, this moves one tour's already-
// generated page into docs/archive/ and marks it). Kept separate from the
// CLI script (which does the actual fs mutation) so the path/content logic
// is unit-testable without touching a real filesystem, same split as
// lib/bootstrap.mjs vs. init-project.mjs.
import path from 'node:path';

const BANNER_MARKER = '<!-- autodocs:archived -->';

// Tour/product pages can now carry a leading YAML frontmatter block (see
// lib/docgen.mjs's renderTourPage `frontmatter` argument / lib/product.mjs's
// buildFrontmatter) — Docusaurus requires frontmatter to be the very first
// thing in the file, so the banner has to land *after* it, not above it, or
// it would silently break sidebar_position/sidebar_label parsing on every
// archived page. Mirrors lib/frontmatter.mjs's FRONTMATTER_RE shape, but
// keeps the frontmatter block as raw text (group 1) instead of parsing it —
// applyArchiveBanner only needs to preserve it verbatim, never read it.
const FRONTMATTER_RE = /^(---\n[\s\S]*?\n---\n?)([\s\S]*)$/;

// Prepended above the page's own `# Title` line. Uses the same HTML-comment
// marker style as the keep-region so applyArchiveBanner can detect it's
// already there (archive-tour.mjs is safe to re-run) without re-parsing the
// whole page. Not a keep-region itself — this banner is generated content,
// written once at archive time and never touched by generate-docs.mjs again
// (archived tours are permanently skipped by the drift gate).
export function buildArchiveBanner() {
  return [
    BANNER_MARKER,
    '> **Archived.** AutoDocs could no longer find this feature in the app — it may have been removed, ' +
      'renamed, or moved. This page is kept for reference and will not be updated further.',
    '',
  ].join('\n');
}

// Idempotent: a page whose content (after any frontmatter) already starts
// with the banner marker is returned unchanged, so re-running
// archive-tour.mjs on an already-archived page (e.g. after a hand edit)
// never stacks a second banner.
export function applyArchiveBanner(markdown) {
  const match = markdown.match(FRONTMATTER_RE);
  const frontmatter = match ? match[1] : '';
  const rest = match ? match[2] : markdown;
  if (rest.startsWith(BANNER_MARKER)) return markdown;
  return `${frontmatter}${buildArchiveBanner()}\n${rest}`;
}

// Where a tour's generated page and images live before/after archiving.
// Images move *with* their relative structure preserved (docs/images/<id>/
// -> docs/archive/images/<id>/), so the `images/<id>/name.png` relative
// paths already inside the markdown stay valid without rewriting a single
// image reference.
export function archivePaths(tourId, { docsDir = 'docs' } = {}) {
  const archiveDir = path.join(docsDir, 'archive');
  return {
    docFrom: path.join(docsDir, `${tourId}.md`),
    docTo: path.join(archiveDir, `${tourId}.md`),
    imagesFrom: path.join(docsDir, 'images', tourId),
    imagesTo: path.join(archiveDir, 'images', tourId),
    archiveDir,
  };
}

// Docusaurus reads docs/ with an autogenerated (folder-based) sidebar (see
// site/sidebars.js's `{type: 'autogenerated', dirName: '.'}`) — dropping a
// _category_.json into docs/archive/ is what gives that folder a real
// "Archive" label and pins it to the bottom of the sidebar instead of
// sorting alphabetically wherever "archive" happens to fall. Harmless to
// write even before a Docusaurus site is scaffolded (init-site just reads it
// later); never overwritten if a human has customized it.
export function buildCategoryJson() {
  return JSON.stringify(
    {
      label: 'Archive',
      position: 999,
      link: {
        type: 'generated-index',
        description: 'Tutorials for features AutoDocs could no longer find in the app. Kept for reference — not updated further.',
      },
    },
    null,
    2,
  ) + '\n';
}
