// Deterministic, security-sensitive parts of first-run project bootstrap
// (see scripts/init-project.mjs, called from skills/document/SKILL.md's
// Step 0). Kept as tested pure functions rather than left to the skill's
// prompt, because getting these wrong has real consequences: a bad baseUrl
// injecting into the generated YAML, or a missing .gitignore entry letting a
// live session cookie or credential get committed.

// A tour/config's `auth` section can hold either scripted-login credentials
// (via env var names) or a storageStatePath pointing at a file full of live
// session cookies. Both must never reach git.
const GITIGNORE_HEADER = '# DocSolace (added automatically by /docsolace:document)';

// Validates and normalizes a base URL, then returns it as a JSON-quoted
// string safe to embed literally in generated YAML. JSON string syntax is a
// valid YAML flow scalar, so this sidesteps YAML-injection from a
// malformed/adversarial baseUrl (e.g. embedded newlines or colons) without
// needing a bespoke YAML-escaping routine.
function safeYamlBaseUrl(baseUrl) {
  if (typeof baseUrl !== 'string' || !baseUrl.trim()) {
    throw new Error('baseUrl is required and must be a non-empty string.');
  }
  let parsed;
  try {
    parsed = new URL(baseUrl);
  } catch {
    throw new Error(
      `"${baseUrl}" doesn't look like a valid URL — DocSolace needs your app's local base URL, e.g. ` +
        `"http://localhost:3000".`,
    );
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error(`"${baseUrl}" must use http:// or https:// (got "${parsed.protocol}").`);
  }
  // Drop a trailing slash so `${baseUrl}${step.path}` (capture.mjs) doesn't
  // produce a double slash for every goto step.
  const normalized = parsed.href.endsWith('/') && parsed.pathname === '/' ? parsed.href.slice(0, -1) : parsed.href;
  return JSON.stringify(normalized);
}

// Renders a real, valid docsolace.config.yaml (not a dead pointer at a file
// that doesn't exist in an installed plugin) with baseUrl/viewports/
// outputDir live, and every optional section (auth — both shapes, masks,
// pixel-diff threshold, seeds) present as commented-out examples adapted
// from this repo's own annotated config.
export function renderAnnotatedConfig(baseUrl) {
  const yamlBaseUrl = safeYamlBaseUrl(baseUrl);
  return `# DocSolace configuration — generated by /docsolace:document's first-run
# bootstrap. See the project README's "Configuring tours and auth" section
# for the full field reference and a worked example.
baseUrl: ${yamlBaseUrl}

# Every capture point is shot at each of these viewports (same page/session —
# only the viewport size changes between shots). The first entry is the
# "primary" one used for any login flow.
viewports:
  desktop:
    width: 1280
    height: 800
  mobile:
    width: 390
    height: 844

outputDir: .docsolace/artifacts

# --- Optional — uncomment and adapt as you need them ---
#
# Selectors masked on every capture (merged with a tour's own \`mask\` list) —
# keeps volatile regions (timestamps, avatars, live counters) out of every
# tour's hash so they don't cause false "changed" results.
# defaultMask:
#   - ".timestamp"
#   - ".user-avatar"
#
# A recaptured screenshot only replaces the committed one in docs/images/
# once the fraction of changed pixels exceeds this threshold.
# pixelDiffThreshold: 0.005
#
# Auth profiles, referenced by a tour's preconditions.auth. Two shapes:
#
# 1) Scripted username/password login — credentials come from env vars
#    (see .env.example), never written here:
# auth:
#   standard-user:
#     loginUrl: /login
#     usernameSelector: "#username"
#     passwordSelector: "#password"
#     submitSelector: "button[type='submit']"
#     usernameEnv: DOCSOLACE_STANDARD_USER_USERNAME
#     passwordEnv: DOCSOLACE_STANDARD_USER_PASSWORD
#     successUrlPattern: "**/dashboard"
#
# 2) OAuth / SSO / magic link / 2FA — record a session once instead of
#    scripting the login (see the README's "If your app doesn't use a plain
#    username/password login"):
# auth:
#   oauth-user:
#     storageStatePath: .docsolace/artifacts/.auth/oauth-user.manual.json
#
# Named seed fixtures referenced by tours' preconditions.seed, for
# reproducible data states. "command" is optional and only ever runs when
# allowSeedCommands is also set to true — see the README.
# seeds:
#   demo-baseline:
#     description: "What this fixture is / how it's seeded."
# allowSeedCommands: false
#
# Bounds for \`/docsolace:document map\`'s dynamic crawl step (see the README's
# "Mapping a whole app automatically"). allowInteractive stays false unless
# you explicitly want the crawler to fill in and submit safe-looking forms
# with synthetic data while mapping — only turn it on against a throwaway/
# dev environment, never production; sensitive fields and destructive
# controls (delete/pay/logout/etc.) are excluded no matter what this is set
# to.
# crawl:
#   maxPages: 50
#   maxDepth: 4
#   allowInteractive: false
#
# Controls generated page layout. primaryViewport (must name a key under
# "viewports" above) stays inline in every step; every other viewport's
# screenshot collapses into a <details> block instead of stacking full-page
# screenshots the reader has to scroll past. Defaults: the first "viewports"
# entry, collapsed on. Set collapseOtherViewports: false to go back to
# showing every viewport inline, labeled. "sections" groups tour pages in the
# generated sidebar (docs/_sidebar.docsolace.json — see the README's "Grouping
# tours in the sidebar"); a tour not listed in any section just sorts into
# one flat "everything else" group instead.
# docs:
#   primaryViewport: desktop
#   collapseOtherViewports: true
#   sections:
#     - label: "Getting started"
#       tours: [login]
#
# Controls \`/docsolace:document product\` — the generated product-level pages
# describing the product itself: overview/getting-started/concepts plus
# configuration/troubleshooting/changelog/decisions where there's something
# real to ground them in (see the README's "Documenting the product
# itself"). "pages" defaults to all seven — an ungrounded one (e.g. no
# CHANGELOG.md, no troubleshooting section in your README, no docs/adr/
# directory) is just skipped and reported, no config needed to turn it off.
# "decisions" needs no config at all — drop Architecture Decision Record
# files under docs/adr/*.md and they're picked up automatically, same as
# CHANGELOG.md; it's the one page where "why" a decision was made is ever in
# scope, and only a decision a human actually wrote down, never inferred
# from code. "sources" adds extra grounding files/globs beyond the standing
# README.md / package.json / .env.example / docsolace.config.yaml /
# CHANGELOG.md / docs/adr/*.md set.
# product:
#   name: "My App"
#   pages: [overview, getting-started, concepts, configuration, troubleshooting, changelog, decisions]
#   sources:
#     - "docs-src/**/*.md"
`;
}

// Idempotently adds any of `entries` missing from `existingContent` under a
// single DocSolace-owned header, without disturbing the rest of the file or
// duplicating entries/headers on repeat calls (e.g. re-running bootstrap).
export function ensureGitignoreEntries(existingContent, entries) {
  const normalizedExisting = existingContent ?? '';
  const existingLines = normalizedExisting.split('\n').map((line) => line.trim());
  const missing = entries.filter((entry) => !existingLines.includes(entry));

  if (missing.length === 0) {
    return normalizedExisting;
  }

  const trimmedExisting = normalizedExisting.replace(/\n+$/, '');
  const needsHeader = !existingLines.includes(GITIGNORE_HEADER);
  const block = [...(needsHeader ? [GITIGNORE_HEADER] : []), ...missing].join('\n');
  const prefix = trimmedExisting.length > 0 ? `${trimmedExisting}\n\n` : '';
  return `${prefix}${block}\n`;
}
